const mockMovies = [
    {
        id: 1,
        title: "Stranger Things",
        name: "Stranger Things",
        original_name: "Stranger Things",
        overview: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
        backdrop_path: "/56v2KjBlU4XaOv9rVYkJu64COIL.jpg",
        poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    },
    {
        id: 2,
        title: "The Witcher",
        name: "The Witcher",
        original_name: "The Witcher",
        overview: "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
        backdrop_path: "/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg",
        poster_path: "/7vjaCdMWasSenpKENh2RAPy2chA.jpg",
    },
    {
        id: 3,
        title: "Money Heist",
        name: "Money Heist",
        original_name: "La casa de papel",
        overview: "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose.",
        backdrop_path: "/gFZriCkpJYS0wnLw08AFSVUTcz.jpg",
        poster_path: "/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
    },
    {
        id: 4,
        title: "Squid Game",
        name: "Squid Game",
        original_name: "Ojing-eo Geim",
        overview: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes.",
        backdrop_path: "/oaGvjB0DvdhXhOAuADfHb261ZHa.jpg",
        poster_path: "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    },
    {
        id: 5,
        title: "Breaking Bad",
        name: "Breaking Bad",
        original_name: "Breaking Bad",
        overview: "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
        backdrop_path: "/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
        poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    },
    {
        id: 6,
        title: "Lucifer",
        name: "Lucifer",
        original_name: "Lucifer",
        overview: "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals.",
        backdrop_path: "/aDBRtunw49UF4XmqeBeCNjzhEBs.jpg",
        poster_path: "/ekZobS2YZ875Ji6RplxiL1qQCNj.jpg",
    },
    {
        id: 7,
        title: "Dark",
        name: "Dark",
        original_name: "Dark",
        overview: "A missing child causes four families to help each other for answers. What they could not imagine is that this mystery would be connected to innumerable other secrets of the small town.",
        backdrop_path: "/3lBDg3i6nn5R2NKjxJPhNwRrPSv.jpg",
        poster_path: "/apbrbWs8M9lyOpJYU5WXkFbk1Z8.jpg",
    },
    {
        id: 8,
        title: "Peaky Blinders",
        name: "Peaky Blinders",
        original_name: "Peaky Blinders",
        overview: "A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby, who means to move up in the world.",
        backdrop_path: "/cz2E9rLpRzYtT2P2056F6hZ5d8.jpg",
        poster_path: "/vUUqzWa2LnHIVqkaKVlVGkWc7Wx.jpg",
    },
];

export default mockMovies;
